#!/usr/bin/env lua

-- LWM Demo Script
-- Bu script LWM'nin nasıl görüneceğini simüle eder

local function print_header()
    print("=" .. string.rep("=", 78) .. "=")
    print("██╗     ██╗    ██╗    ███╗   ███╗")
    print("██║     ██║    ██║    ████╗ ████║")
    print("██║     ██║ █╗ ██║    ██╔████╔██║")
    print("██║     ██║███╗██║    ██║╚██╔╝██║")
    print("███████╗╚███╔███╔╝    ██║ ╚═╝ ██║")
    print("╚══════╝ ╚══╝╚══╝     ╚═╝     ╚═╝")
    print("")
    print("Lua Window Manager - Modern Pencere Yöneticisi")
    print("=" .. string.rep("=", 78) .. "=")
end

local function print_theme_info()
    print("\n🎨 TEMA BİLGİLERİ:")
    print("   • Arka Plan: #1a1a1a (Koyu gri)")
    print("   • Ön Plan: #ffffff (Beyaz)")
    print("   • Odak Rengi: #00ff88 (Neon yeşil)")
    print("   • Kenarlık: #333333 (Gri)")
    print("   • Font: JetBrains Mono 10")
end

local function print_widgets()
    print("\n📱 WIDGET'LAR:")
    print("   ┌─────────────────────────────────────────────────────────────┐")
    print("   │ [🏠] [1] [2] [3] [4] [5] [6] [7] [8] [9] [🌐] [📝] [📁]     │")
    print("   │                                                             │")
    print("   │                    [Aktif Pencereler]                      │")
    print("   │                                                             │")
    print("   │ [CPU: 45%] [RAM: 67%] [🌡️ 65°C] [📶 ↓2.1M ↑1.8M] [🔊 75%] │")
    print("   │ [🔋 85%] [🌤️ 22°C] [📅] [🎵 Spotify] [📧 3] [⏱️ 2h] [🔔 2] │")
    print("   │ [🕐 15:30] [📊]                                              │")
    print("   └─────────────────────────────────────────────────────────────┘")
end

local function print_keybindings()
    print("\n⌨️  KLVYE KISAYOLLARI:")
    print("   ┌─────────────────────────────────────────────────────────────┐")
    print("   │ Genel:                                                      │")
    print("   │   Super + S     → Yardım menüsü                            │")
    print("   │   Super + Enter → Terminal aç                              │")
    print("   │   Super + R     → Komut çalıştır                           │")
    print("   │   Super + W     → Ana menü                                 │")
    print("   │                                                             │")
    print("   │ Pencere Yönetimi:                                           │")
    print("   │   Super + J/K   → Sonraki/önceki pencere                   │")
    print("   │   Super + F     → Tam ekran                                │")
    print("   │   Super + Shift + C → Pencereyi kapat                      │")
    print("   │   Super + Space → Layout değiştir                          │")
    print("   │                                                             │")
    print("   │ Tag Yönetimi:                                               │")
    print("   │   Super + 1-9   → Tag'e geç                                │")
    print("   │   Super + Left/Right → Önceki/sonraki tag                  │")
    print("   └─────────────────────────────────────────────────────────────┘")
end

local function print_layouts()
    print("\n🎯 LAYOUT'LAR:")
    print("   ┌─────────────────────────────────────────────────────────────┐")
    print("   │ 1. Floating  → Yüzen pencereler                            │")
    print("   │ 2. Tile      → Döşeme düzeni                               │")
    print("   │ 3. Fair      → Adil düzen                                  │")
    print("   │ 4. Spiral    → Spiral düzen                                │")
    print("   │ 5. Max       → Maksimize                                   │")
    print("   │ 6. Fullscreen → Tam ekran                                  │")
    print("   │ 7. Magnifier → Büyüteç                                     │")
    print("   │ 8. Corner    → Köşe düzeni                                 │")
    print("   └─────────────────────────────────────────────────────────────┘")
end

local function print_features()
    print("\n🚀 ÖZELLİKLER:")
    print("   ┌─────────────────────────────────────────────────────────────┐")
    print("   │ ✓ Modern koyu tema                                         │")
    print("   │ ✓ Yuvarlatılmış köşeler                                    │")
    print("   │ ✓ Gradient efektleri                                       │")
    print("   │ ✓ Gölge efektleri                                          │")
    print("   │ ✓ Blur efektleri                                           │")
    print("   │ ✓ 14 farklı widget                                         │")
    print("   │ ✓ 50+ klavye kısayolu                                      │")
    print("   │ ✓ 13 farklı layout                                         │")
    print("   │ ✓ Çoklu ekran desteği                                      │")
    print("   │ ✓ Otomatik başlatma                                        │")
    print("   │ ✓ Hata ayıklama sistemi                                    │")
    print("   │ ✓ Performans optimizasyonu                                 │")
    print("   └─────────────────────────────────────────────────────────────┘")
end

local function print_installation()
    print("\n📦 KURULUM:")
    print("   ┌─────────────────────────────────────────────────────────────┐")
    print("   │ Ubuntu/Debian:                                             │")
    print("   │   sudo apt install awesome awesome-extra                   │")
    print("   │                                                             │")
    print("   │ Arch Linux:                                                │")
    print("   │   sudo pacman -S awesome vicious playerctl                 │")
    print("   │                                                             │")
    print("   │ Fedora:                                                    │")
    print("   │   sudo dnf install awesome vicious playerctl               │")
    print("   │                                                             │")
    print("   │ LWM Kurulumu:                                              │")
    print("   │   ./install.sh                                             │")
    print("   └─────────────────────────────────────────────────────────────┘")
end

local function print_system_requirements()
    print("\n💻 SİSTEM GEREKSİNİMLERİ:")
    print("   ┌─────────────────────────────────────────────────────────────┐")
    print("   │ • AwesomeWM 4.3+                                           │")
    print("   │ • Lua 5.4+                                                 │")
    print("   │ • X11                                                       │")
    print("   │ • Vicious (widget'lar için)                                │")
    print("   │ • Playerctl (müzik kontrolü için)                          │")
    print("   │ • Alacritty (terminal)                                     │")
    print("   │ • JetBrains Mono font                                      │")
    print("   └─────────────────────────────────────────────────────────────┘")
end

local function print_status()
    print("\n📊 DURUM:")
    print("   ┌─────────────────────────────────────────────────────────────┐")
    print("   │ 🟢 Tema dosyası hazır                                       │")
    print("   │ 🟢 Widget'lar hazır                                         │")
    print("   │ 🟢 Konfigürasyon dosyası hazır                             │")
    print("   │ 🟢 Kurulum script'i hazır                                   │")
    print("   │ 🟢 Dokümantasyon hazır                                      │")
    print("   │                                                             │")
    print("   │ ⚠️  AwesomeWM kurulumu gerekli                              │")
    print("   │ ⚠️  X11 desteği gerekli                                     │")
    print("   └─────────────────────────────────────────────────────────────┘")
end

local function print_next_steps()
    print("\n🎯 SONRAKI ADIMLAR:")
    print("   ┌─────────────────────────────────────────────────────────────┐")
    print("   │ 1. AwesomeWM kurun                                         │")
    print("   │ 2. LWM dosyalarını ~/.config/awesome/ dizinine kopyalayın   │")
    print("   │ 3. Oturumu kapatın ve yeniden giriş yapın                   │")
    print("   │ 4. AwesomeWM'yi seçin                                       │")
    print("   │ 5. Super + S ile yardım menüsünü açın                       │")
    print("   │                                                             │")
    print("   │ Daha fazla bilgi için README.md dosyasını okuyun            │")
    print("   └─────────────────────────────────────────────────────────────┘")
end

local function print_footer()
    print("\n" .. string.rep("=", 80))
    print("🎉 LWM Demo tamamlandı! Modern ve profesyonel pencere yöneticisi hazır.")
    print("📧 Sorularınız için: kullanici@example.com")
    print("🌐 GitHub: https://github.com/kullanici/lwm")
    print(string.rep("=", 80))
end

-- Ana fonksiyon
local function main()
    print_header()
    print_theme_info()
    print_widgets()
    print_keybindings()
    print_layouts()
    print_features()
    print_installation()
    print_system_requirements()
    print_status()
    print_next_steps()
    print_footer()
end

-- Script'i çalıştır
main() 